version: '3'
services:
  db:
    container_name:
      workload-master-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    networks:
      - workload-ICTIS-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    container_name: workload-master-server
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3010:3010'
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PWD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=db
    networks:
      - workload-ICTIS-network

#  nginx:
#    container_name: workload-master-nginx
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    depends_on:
#      - client
#    restart: always
#    ports:
#      - "80:80"
#    networks:
#      - workload-ICTIS-network
  
  client:
    depends_on:
      - server
    container_name: workload-master-client
    build:
      context: ./workload
      dockerfile: Dockerfile
    ports:
      - '80:80'
    restart: always
    networks:
    - workload-ICTIS-network
 
networks:
  workload-ICTIS-network:

volumes:
  pgdata: