version: '3'
services:
  db:
    container_name:
      workload-ICTIS-db
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    networks:
      - workload-ICTIS-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    container_name: workload-ICTIS-server
    build:
      context: ./app/
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - '3010:3010'
    env_file:
      - ./.env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PWD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=db
    networks:
      - workload-ICTIS-network
      - workload-ICTIS-frontend
  
  client:
    depends_on:
      - server
    container_name: workload-ICTIS-client
    build:
      context: ./workload/
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    networks:
    - workload-ICTIS-frontend
  
networks:
  workload-ICTIS-network:
  workload-ICTIS-frontend:

volumes:
  pgdata: