export const workloads = [
    {
        department: 13,
        discipline: 'Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 14,
        discipline: '14 Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 16,
        discipline: '16 Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 17,
        discipline: '17 Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 18,
        discipline: '18 Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 19,
        discipline: '19 Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 24,
        discipline: '24 Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 2,
        discipline:
            'Практика по получению профессиональных умений и опыта  профессиональной деятельности (производственная практика)',
        workload: 'Прочая практика',
        groups: 'КТ09.05.01.65., Основной поток, Очная',
        block: 'Б2.П',
        semester: '10с',
        period: 2,
        curriculum: '000166459',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Специалист',
        specialty: 'Применение и эксплуатация автоматизированных систем специального назначения',
        core: 'Автоматизированные системы обработки информации и управления (ВУС 530200)',
        numberOfStudents: 10,
        hours: 620.35,
        audienceHours: 410.35,
        ratingControlHours: 160.31,
        comment: 'Text123',
        isSplit: true,
        originalId: null,
        educatorId: null,
        isOid: true,
    },
    {
        department: 6,
        discipline: 'Тест Каф 1',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 1,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 123.3,
        audienceHours: 123.3,
        ratingControlHours: 0,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 6,
        discipline: 'Тест ОИД 1',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 1,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 321.3,
        audienceHours: 321.3,
        ratingControlHours: 0,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: true,
    },
    {
        department: 6,
        discipline: 'Тест ОИД 2',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 321.3,
        audienceHours: 321.3,
        ratingControlHours: 0,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: true,
    },
];

export const educators = [
    {
        name: 'Бучнев Максим Тимофеевич',
        department: 13,
        email: 'mbuchnev@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Сиверин Никита Александрович',
        department: 11,
        email: 'siverin@sfedu.ru',
        position: 5,
        rate: 0.4,
    },
    {
        name: 'Капылов Никита Максимович',
        department: 6,
        email: 'kapylov@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {

        name: 'Тоноян Артур Арменович',
        department: 6,
        email: 'atonoian@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Суханов Александр Сергеевич',
        department: 11,
        email: 'sukhanov@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
];
