export const workloads = [
    {
        department: 13,
        discipline: 'Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 14,
        discipline: '14 Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 16,
        discipline: '16 Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 17,
        discipline: '17 Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 18,
        discipline: '18 Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 19,
        discipline: '19 Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 24,
        discipline: '24 Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 2,
        discipline:
            'Практика по получению профессиональных умений и опыта  профессиональной деятельности (производственная практика)',
        workload: 'Прочая практика',
        groups: 'КТ09.05.01.65., Основной поток, Очная',
        block: 'Б2.П',
        semester: '10с',
        period: 2,
        curriculum: '000166459',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Специалист',
        specialty: 'Применение и эксплуатация автоматизированных систем специального назначения',
        core: 'Автоматизированные системы обработки информации и управления (ВУС 530200)',
        numberOfStudents: 10,
        hours: 620.35,
        audienceHours: 410.35,
        ratingControlHours: 160.31,
        comment: 'Text123',
        isSplit: true,
        originalId: null,
        educatorId: null,
        isOid: true,
    },
    {
        department: 6,
        discipline: 'Тест Каф 1',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 1,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 123.3,
        audienceHours: 123.3,
        ratingControlHours: 0,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 6,
        discipline: 'Тест ОИД 1',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 1,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 321.3,
        audienceHours: 321.3,
        ratingControlHours: 0,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: true,
    },
    {
        department: 6,
        discipline: 'Тест ОИД 2',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 321.3,
        audienceHours: 321.3,
        ratingControlHours: 0,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: true,
    },
];

export const educators = [
    {
        name: 'Бучнев Максим Тимофеевич',
        department: 13,
        email: 'mbuchnev@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Сиверин Никита Александрович',
        department: 11,
        email: 'siverin@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Капылов Никита Максимович',
        department: 6,
        email: 'kapylov@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тоноян Артур Арменович',
        department: 6,
        email: 'atonoian@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Суханов Александр Сергеевич',
        department: 11,
        email: 'sukhanov@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест METHODIST',
        department: 99,
        email: 'test1@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест LECTURER',
        department: 1,
        email: 'test2@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест DEPARTMENT_HEAD',
        department: 1,
        email: 'test3@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест DIRECTORATE ИКТИБ',
        department: 1,
        email: 'test4ictis@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест DIRECTORATE ИРТСУ',
        department: 1,
        email: 'test4rtf@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест DIRECTORATE ИНЕП',
        department: 1,
        email: 'test4inep@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест EDUCATOR',
        department: 1,
        email: 'test5@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест UNIT_ADMIN',
        department: 99,
        email: 'test6@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест DEPUTY_DIRECTORATE ИКТИБ',
        department: 1,
        email: 'test7ictis@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест DEPUTY_DIRECTORATE ИРТСУ',
        department: 1,
        email: 'test7rtf@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест DEPUTY_DIRECTORATE ИНЕП',
        department: 1,
        email: 'test7inep@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест DEPUTY_DEPARTMENT_HEAD',
        department: 1,
        email: 'test8@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест GIGA_ADMIN',
        department: 99,
        email: 'test9@sfedu.ru',
        position: 5,
        rate: 0.5,
    },
    {
        name: 'Тест GOD',
        department: 99,
        email: 'test10@sfedu.ru',
        position: 5,
        rate: 0.5,
    }
];

export const users = [
    
    {
        name: 'Тест METHODIST',
        login: 'test1@sfedu.ru',
        role: 1,
        institutionalAffiliation: 1,
    },
    {
        name: 'Тест LECTURER',
        login: 'test2@sfedu.ru',
        role: 2,
        institutionalAffiliation: 1,
    },
    {
        name: 'Тест DEPARTMENT_HEAD',
        login: 'test3@sfedu.ru',
        role: 3,
        institutionalAffiliation: 1,
    },
    {
        name: 'Тест DIRECTORATE ИКТИБ',
        login: 'test4ictis@sfedu.ru',
        role: 4,
        institutionalAffiliation: 1,
    },
    {
        name: 'Тест DIRECTORATE ИРТСУ',
        login: 'test4rtf@sfedu.ru',
        role: 4,
        institutionalAffiliation: 2,
    },
    {
        name: 'Тест DIRECTORATE ИНЕП',
        login: 'test4inep@sfedu.ru',
        prole: 4,
        institutionalAffiliation: 3,
    },
    {
        name: 'Тест EDUCATOR',
        login: 'test5@sfedu.ru',
        role: 5,
        institutionalAffiliation: 1,
    },
    {
        name: 'Тест UNIT_ADMIN',
        login: 'test6@sfedu.ru',
        role: 6,
        institutionalAffiliation: 1,
    },
    {
        name: 'Тест DEPUTY_DIRECTORATE ИКТИБ',
        login: 'test7ictis@sfedu.ru',
        role: 7,
        institutionalAffiliation: 1,
    },
    {
        name: 'Тест DEPUTY_DIRECTORATE ИРТСУ',
        login: 'test7rtf@sfedu.ru',
        role: 7,
        institutionalAffiliation: 2,
    },
    {
        name: 'Тест DEPUTY_DIRECTORATE ИНЕП',
        login: 'test7inep@sfedu.ru',
        role: 7,
        institutionalAffiliation: 3,
    },
    {
        name: 'Тест DEPUTY_DEPARTMENT_HEAD',
        login: 'test8@sfedu.ru',
        role: 8,
        institutionalAffiliation: 1,
    },
    {
        name: 'Тест GIGA_ADMIN',
        login: 'test9@sfedu.ru',
        role: 9,
        institutionalAffiliation: 1,
    },
    {
        name: 'Тест GOD',
        login: 'test10@sfedu.ru',
        role: 10,
        institutionalAffiliation: 1,
    }
]