export const workloads = [
    {
        department: 6,
        discipline: 'Подготовка к процедуре защиты и защита выпускной квалификационной работы',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 500.5,
        audienceHours: 500.5,
        ratingControlHours: 500.5,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 2,
        discipline:
            'Практика по получению профессиональных умений и опыта  профессиональной деятельности (производственная практика)',
        workload: 'Прочая практика',
        groups: 'КТ09.05.01.65., Основной поток, Очная',
        block: 'Б2.П',
        semester: '10с',
        period: 2,
        curriculum: '000166459',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Специалист',
        specialty: 'Применение и эксплуатация автоматизированных систем специального назначения',
        core: 'Автоматизированные системы обработки информации и управления (ВУС 530200)',
        numberOfStudents: 10,
        hours: 620.35,
        audienceHours: 410.35,
        ratingControlHours: 160.31,
        comment: 'Text123',
        isSplit: true,
        originalId: null,
        educatorId: null,
        isOid: true,
    },
    {
        department: 6,
        discipline: 'Тест Каф 1',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 1,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 123.3,
        audienceHours: 123.3,
        ratingControlHours: 0,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: false,
    },
    {
        department: 6,
        discipline: 'Тест ОИД 1',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 1,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 321.3,
        audienceHours: 321.3,
        ratingControlHours: 0,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: true,
    },
    {
        department: 6,
        discipline: 'Тест ОИД 2',
        workload: 'Защита ВКР',
        groups: 'КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, КТ09.03.04.62.03, Основной поток, Очная',
        block: 'Б3',
        semester: '8с',
        period: 2,
        curriculum: '000166064, 000166743, 000167265, 000169105',
        curriculumUnit: 'ИКТИБ',
        formOfEducation: 'Очная',
        levelOfTraining: 'Бакалавр',
        specialty: 'Программная инженерия',
        core: 'Методы и средства разработки программного обеспечения',
        numberOfStudents: 53,
        hours: 321.3,
        audienceHours: 321.3,
        ratingControlHours: 0,
        comment: 'Text',
        isSplit: false,
        originalId: null,
        educatorId: null,
        isOid: true,
    },
];

export const educators = [
    {
        name: 'Алексеев Кирилл Николаевич',
        department: 1,
        position: 5,
        typeOfEmployment: 1,
        rate: 0.5,
    },
    {
        name: 'Беспалов Дмитрий Анатольевич',
        department: 1,
        position: 5,
        typeOfEmployment: 3,
        rate: 1,
    },
    {
        name: 'Орлов Руслан Александрович',
        department: 6,
        position: 5,
        typeOfEmployment: 1,
        rate: 0.5,
    },
    {
        name: 'Бучнев Максим Тимофеевич',
        department: 6,
        position: 5,
        typeOfEmployment: 1,
        rate: 0.5,
    },
];
