version: '3'
services:
  db:
    container_name:
      workload-ictis-db
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    networks:
      - workload-ICTIS-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    container_name: workload-ictis-server
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - '3002:3002'
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PWD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    networks:
      - workload-ICTIS-network

  client:
    depends_on:
      - server
    container_name: workload-master-client
    build:
      context: ../workload
      dockerfile: Dockerfile
    ports:
      - '82:82'
    restart: always
    networks:
      - workload-ICTIS-network

networks:
  workload-ICTIS-network:

volumes:
  pgdata: