// заглушка таблицы
export const plagData = [
  {
    id: "d1sb7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
    discipline: "Введение в программирование",
    workload: 5,
    groups: "ИС-21",
    department: "Информационных систем и технологий",
    block: "Б1.О.01",
    semester: 1,
    period: "2022/2023",
    curriculum: "09.03.02",
    curriculumUnit: "Институт информационных технологий",
    formOfEducation: "Очная",
    levelOfTraining: "Бакалавриат",
    specialty: "Информационные системы и технологии",
    core: "Информационные системы и технологии",
    numberOfStudents: 25,
    hours: 180,
    audienceHours: 90,
    ratingControlHours: 36,
    educator: {
      id: "ed1b7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
      name: "Иванов И.И.",
    },
    isOid: true,
  },
  {
    id: "d2sb7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
    discipline: "Базы данных",
    workload: 4,
    groups: "ИС-21",
    department: "Информационных систем и технологий",
    block: "Б1.О.02",
    semester: 3,
    period: "2022/2023",
    curriculum: "09.03.02",
    curriculumUnit: "Институт информационных технологий",
    formOfEducation: "Очная",
    levelOfTraining: "Бакалавриат",
    specialty: "Информационные системы и технологии",
    core: "Информационные системы и технологии",
    numberOfStudents: 25,
    hours: 144,
    audienceHours: 72,
    ratingControlHours: 28,
    educator: {
      id: "ed2b7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
      name: "Петров П.П.",
    },
    isOid: false,
  },
  {
    id: "d3sb7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
    discipline: "Алгоритмы и структуры данных",
    workload: 5,
    groups: "ИС-21",
    department: "Информационных систем и технологий",
    block: "Б1.О.03",
    semester: 2,
    period: "2022/2023",
    curriculum: "09.03.02",
    curriculumUnit: "Институт информационных технологий",
    formOfEducation: "Очная",
    levelOfTraining: "Бакалавриат",
    specialty: "Информационные системы и технологии",
    core: "Информационные системы и технологии",
    numberOfStudents: 25,
    hours: 180,
    audienceHours: 90,
    ratingControlHours: 36,
    educator: {
      id: "ed3b7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
      name: "Сидоров С.С.",
    },
    isOid: true,
  },
  {
    id: "d4sb7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
    discipline: "Объектно-ориентированное программирование",
    workload: 4,
    groups: "ИС-21",
    department: "Информационных систем и технологий",
    block: "Б1.О.04",
    semester: 2,
    period: "2022/2023",
    curriculum: "09.03.02",
    curriculumUnit: "Институт информационных технологий",
    formOfEducation: "Очная",
    levelOfTraining: "Бакалавриат",
    specialty: "Информационные системы и технологии",
    core: "Информационные системы и технологии",
    numberOfStudents: 25,
    hours: 144,
    audienceHours: 72,
    ratingControlHours: 28,
    educator: {
      id: "ed4b7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
      name: "Кузнецов К.К.",
    },
    isOid: false,
  },
  {
    id: "d5sb7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
    discipline: "Компьютерные сети",
    workload: 3,
    groups: "ИС-21",
    department: "Информационных систем и технологий",
    block: "Б1.О.05",
    semester: 4,
    period: "2022/2023",
    curriculum: "09.03.02",
    curriculumUnit: "Институт информационных технологий",
    formOfEducation: "Очная",
    levelOfTraining: "Бакалавриат",
    specialty: "Информационные системы и технологии",
    core: "Информационные системы и технологии",
    numberOfStudents: 25,
    hours: 108,
    audienceHours: 54,
    ratingControlHours: 22,
    educator: {
      id: "ed5b7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
      name: "Смирнова С.С.",
    },
    isOid: true,
  },
  {
    id: "d7sb7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
    discipline: "Разработка веб-приложений",
    workload: 5,
    groups: "ИС-21",
    department: "Информационных систем и технологий",
    block: "Б1.О.07",
    semester: 4,
    period: "2022/2023",
    curriculum: "09.03.02",
    curriculumUnit: "Институт информационных технологий",
    formOfEducation: "Очная",
    levelOfTraining: "Бакалавриат",
    specialty: "Информационные системы и технологии",
    core: "Информационные системы и технологии",
    numberOfStudents: 25,
    hours: 180,
    audienceHours: 90,
    ratingControlHours: 36,
    educator: {
      id: "ed7b7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
      name: "Соколов С.С.",
    },
    isOid: true,
  },
  {
    id: "d8sb7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
    discipline: "Информационная безопасность",
    workload: 3,
    groups: "ИС-21",
    department: "Информационных систем и технологий",
    block: "Б1.О.08",
    semester: 5,
    period: "2022/2023",
    curriculum: "09.03.02",
    curriculumUnit: "Институт информационных технологий",
    formOfEducation: "Очная",
    levelOfTraining: "Бакалавриат",
    specialty: "Информационные системы и технологии",
    core: "Информационные системы и технологии",
    numberOfStudents: 25,
    hours: 108,
    audienceHours: 54,
    ratingControlHours: 22,
    educator: {
      id: "ed8b7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
      name: "Михайлов М.М.",
    },
    isOid: false,
  },
  {
    id: "d9sb7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
    discipline: "Управление IT-проектами",
    workload: 4,
    groups: "ИС-21",
    department: "Информационных систем и технологий",
    block: "Б1.О.09",
    semester: 6,
    period: "2022/2023",
    curriculum: "09.03.02",
    curriculumUnit: "Институт информационных технологий",
    formOfEducation: "Очная",
    levelOfTraining: "Бакалавриат",
    specialty: "Информационные системы и технологии",
    core: "Информационные системы и технологии",
    numberOfStudents: 25,
    hours: 144,
    audienceHours: 72,
    ratingControlHours: 28,
    educator: {
      id: "ed9b7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
      name: "Новиков Н.Н.",
    },
    isOid: true,
  },
  {
    id: "d10sb7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
    discipline: "Разработка мобильных приложений",
    workload: 4,
    groups: "ИС-21",
    department: "Информационных систем и технологий",
    block: "Б1.О.10",
    semester: 5,
    period: "2022/2023",
    curriculum: "09.03.02",
    curriculumUnit: "Институт информационных технологий",
    formOfEducation: "Очная",
    levelOfTraining: "Бакалавриат",
    specialty: "Информационные системы и технологии",
    core: "Информационные системы и технологии",
    numberOfStudents: 25,
    hours: 144,
    audienceHours: 72,
    ratingControlHours: 28,
    educator: {
      id: "ed10b7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
      name: "Борисова Б.Б.",
    },
    isOid: false,
  },
  {
    id: "d12sb7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
    discipline: "Облачные технологии",
    workload: 3,
    groups: "ИС-21",
    department: "Информационных систем и технологий",
    block: "Б1.О.12",
    semester: 7,
    period: "2022/2023",
    curriculum: "09.03.02",
    curriculumUnit: "Институт информационных технологий",
    formOfEducation: "Очная",
    levelOfTraining: "Бакалавриат",
    specialty: "Информационные системы и технологии",
    core: "Информационные системы и технологии",
    numberOfStudents: 25,
    hours: 108,
    audienceHours: 54,
    ratingControlHours: 22,
    educator: {
      id: "ed12b7c9d-4e57-4b8b-9c4e-b2c7f3d9e6f8",
      name: "Лебедева Л.Л.",
    },
    isOid: false,
  },
];
